### ISSUE TITLE
Revoke-delegate working and displaying on API, throws error on explorer

### ISSUE THREAD

**Issue by ASuciuX** [hirosystems/explorer#1557]
**Describe the bug**
Hello, during the end user testing for pox4 using lockstack for the delegate and revoke-delegate to a principal, I found this:

All revoke delegate calls I have throw an error on explorer when opening the tx, works on api. Here is the [address](https://explorer.hiro.so/address/STTA4HM206NSGCZ3HDE8ZN4YY4PKYYWHX6MZJYWW?chain=testnet) to select from the revoke calls.

This is the error
```TypeError: Cannot read properties of undefined (reading 'includes')```

Transaction ID 0x8a69ba543fd1ff3f7d0163414443ac6e2608b28f8dc67473fb638e54538da61d
Network Testnet
Address STTA4HM206NSGCZ3HDE8ZN4YY4PKYYWHX6MZJYWW
Block# 153245 ( also on other revoke-delegate calls )

Explorer Tx link: https://explorer.hiro.so/txid/0x8a69ba543fd1ff3f7d0163414443ac6e2608b28f8dc67473fb638e54538da61d?chain=testnet
API Tx link: https://stacks-node-api.testnet.stacks.co/extended/v1/tx/0x8a69ba543fd1ff3f7d0163414443ac6e2608b28f8dc67473fb638e54538da61d

**To Reproduce**
1. Go to explorer tx link mentioned above
2. See error

**Expected behavior**
To have the tx displayed. 

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Browser chrome 
 - Version Version 120.0.6099.71 (Official Build) (arm64)

**Additional context**
Add any other context about the problem here:

**Comment by BLuEScioN** [comment]
Both the explorer tx link and the api tx link now say that the tx doesn't exist.

And I do not see 

> TypeError: Cannot read properties of undefined (reading 'includes')

when I use your explorer link to the address.

Previously, we had a bug where the account page showed an error when the address was a valid STX address but it didn't have any txs. That issue has since been fixed. 
The API says your address has no txs, so it makes sense that the API would show an error.
