### ISSUE TITLE
Update to new logo color

### ISSUE THREAD

**Issue by cuevasm** [hirosystems/explorer#1744]
![image](https://github.com/user-attachments/assets/fb01f63b-1dec-456b-a4d3-596a008de3c3)

Would be great if we can update these 🙏

https://stacks.co/brand

**Comment by andresgalante** [comment]
@ginny-d should we do this now?

**Comment by ginny-d** [comment]
Sure, but please note that, while we're working in the redesign, **it will look very bad** in some parts. I appreciate the patience!

If I'm not mistaken, we have a semantic token for a color named "brand", we could change that to be: `brand: '#FC6432'`instead of `brand: 'purple.600'`

As for the logo, I'm sending attached the SVG to replace:
![stx-icon](https://github.com/user-attachments/assets/1ceb2ca2-8c9d-43b9-84cb-471d858a85a5)

**Comment by BLuEScioN** [comment]
@ginny-d can you link me to a figma with this svg. I can't get the svg from this

**Comment by cuevasm** [comment]
Hey peeps, this looks great, noticing the blue in this view still tho:
![image](https://github.com/user-attachments/assets/5fa14af7-5722-4460-bf21-656de3682608)
https://explorer.hiro.so/txid/0xa9f82d9c71e32ca49465b55090c4422a5774073823a0876c9d7abd1950adcab2?chain=mainnet

The favicon is also still purple (yes, have cleared cache)

Also can't tell which token in this list is actually STX, not sure if there's an indicator we could add for that to differentiate it from knockoffs, but whichever it is, it should be orange too 🙏 https://explorer.hiro.so/tokens?chain=mainnet
