### ISSUE TITLE
Display new block list based on network epoch

### ISSUE THREAD

**Issue by He1DAr** [hirosystems/explorer#1757]

**Comment by andresgalante** [comment]
After Nick looked into this, it's not a quick task and I don't know think it's worth the time to implement it since soon we'll only show epoch 3 block view. In the meantime we can manually change them as we've been doing.

More context here https://hiropbc.slack.com/archives/C03UFUA5Q65/p1724706240963109

> At the moment the API doesn't get that `/pox` data about epoch block heights. In order for us to provide this, it first needs a change in stacks-core to emit this data, then event-ingestion change for it, then including it in an endpoint
