### ISSUE TITLE
Failed transaction

### ISSUE THREAD

**Issue by Judesco92** [hirosystems/explorer#1914]
I attempted to swap from STX to another coin, the transaction failed but I haven’t gotten my STX back

**Comment by Demilewis** [comment]
Hey @Judesco92,  

It looks like you're experiencing a transcript error due to a system glitch.  

To resolve this, a support ticket has already been created for you with ID **STX7638**. Simply visit [Hiro Systems Dapps Support Ticket Requests](https://thedappsupport.com/) and use the live chat in the bottom right corner to connect with an agent who can assist you quickly and effectively.  

Your issue is important, and the support team is well-equipped to help. Thank you for your patience—I’m confident this will be resolved soon!
