### ISSUE TITLE
Show receipt activity item for send-many events

### ISSUE THREAD

**Issue by psq** [hirosystems/explorer#373]
If you take a look at this transaction https://explorer.stacks.co/txid/0x9bfd994d8185a42710269f387bcf34e72b19bfd5e5e2a5b8a78b7731519c1ea4?chain=mainnet, which sent rewards from one of the testnet mining contest, on that page you can see the amounts transferred.

Now, if you go to one of the recipients, say https://explorer.stacks.co/address/SP2ZHPZXJ39JT5B8HFGYNP9KT6SEYYDH4AP9PF9ZC?chain=mainnet you can see it received some STX via `send-many`, but unless you go through the original page above and find your address, you can't tell how much was received.  I didn't pick the first ones, as these had only one transaction, so you could tell the amount by looking at the balance.

It would be much more helpful if you tell from the recipient's page how much was received (or I guess the same would be the case for sending to a contract?)

<img width="926" alt="Screen Shot 2021-02-17 at 12 07 27 AM" src="https://user-images.githubusercontent.com/255/108174415-42ad2600-70b4-11eb-8511-5b51e6b2027a.png">

**Comment by aulneau** [comment]
@zone117x do you know of any work currently being tracked to have these types of events be exposed in the api like other token transfers?

**Comment by zone117x** [comment]
@aulneau so the events are exposed, see https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/0x9bfd994d8185a42710269f387bcf34e72b19bfd5e5e2a5b8a78b7731519c1ea4

But they are not artificially transformed in the API to appear exactly like a `stx-transfer` tx type -- it's a totally different set of data and simply cannot be shoehorned into the existing APIs that return a parsed transaction object. 

However, I do think there should be an API endpoint (new or modify an existing) where an `address` can be specified, and the asset transfers associated with the address are specified separately. So, for example, instead of paginating through the list of events in one of these send-many txs to find ones associated with an address you're displaying, the API would aggregate and include that data for you. 

This is actually required for the transactions in block number 1, because it has a transaction with an extremely large set of events that would be very taxing to paginate on the client and server.

There is an issue related to this: https://github.com/blockstack/stacks-blockchain-api/issues/369

I'll continue by response in that issue ^
