### ISSUE TITLE
Prevent /v2 from being queried too often on accounts page

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/explorer#586]
**Is your feature request related to a problem? Please describe.**
On the explorer's `address` page ([example](https://explorer.stacks.co/address/SM2MARAVW6BEJCD13YV2RHGYHQWT7TDDNMNRB1MVT?chain=mainnet)), the `v2` endpoint `https://stacks-node-api.stacks.co/v2/accounts/XXXXXXXXX?proof=0&unanchored=true` is fetched roughly every 10 seconds. With so many people using the explorer, this could create RPC congestion for stacks-nodes.

**Describe the solution you'd like**
I'm not sure what data is being used from `https://stacks-node-api.stacks.co/v2/accounts/XXXXXXXXX?proof=0&unanchored=true` every 10 seconds, but can it be obtained from a `v1` endpoint instead? `v1` is much more performant, and will help stacks-nodes propagate transactions faster with less RPC congestion.

Additionally, I feel a 10 second refresh might be too frequent. If this refresh interval could be changed via environment variable, it would allow those hosting it to configure a refresh interval that balances speed and traffic.

**Side question** - Looks like a few other `v1` endpoints are being called at regular intervals in the explorer as well. Can the explorer  start leveraging websockets? The API now supports websockets, which would be more performant than standard HTTP requests, and data would be transmitted as soon as it's received.

cc @zone117x @rafaelcr

**Comment by rafaelcr** [comment]
Please let me know if I can be of any help with the API websockets and/or if you need a new event added.

**Comment by markmhx** [comment]
One quick fix here would be to remove auto-refresh and simply place a "Refresh" button.

We can also investigate just how we're using this `v2` endpoint and whether we can switch it out for `v1` or WebSockets, but that might take more time than we want to risk in case we have another surge in the meantime.

Moving to design so @eugeniadigon can place a "Refresh" button as an option on hand.

**Comment by CharlieC3** [comment]
@markmhx I think a manual refresh button would end up helping quite a bit for the interim, as most don't need to refresh every so often.

It may detract a tiny bit from the user experience though. So in the long run if it can be swapped out for a `v1` call or websockets, it would be nice to have auto-refresh re-implemented with that optimization, along with the adjustable env var mentioned in the description.

**Comment by markmhx** [comment]
@He1DAr might you be resolving this issue implicitly as part of your current performance work already? If not, is this something that would fit naturally into that work?

If you can improve the automatic loading performance here, then we should keep the same UX. Otherwise I'll assign to @landitus for modification to manual loading.

**Comment by beguene** [comment]
Summary of what we can and should do here

1. reduce the fetch frequency for /account (quick win),
2. use v1 instead of v2 just for this endpoint /accounts
3. prevent refetch on windowFocus (to be discussed from a UX perspective)
4. use v1 instead of v2 everywhere else
5. use websockets instead

The solution for now is to address 1) and 2) and prioritise 3), 4) and 5)
