### ISSUE TITLE
Websocket support to the backend API

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/explorer#620]
**Is your feature request related to a problem? Please describe.**
Individual HTTP requests can bog down a backend API under high traffic, causing performance issues and OOM errors for the API server.

**Describe the solution you'd like**
The API now supports websockets, which exhibit much better performance than individual HTTP requests. Implement websocket/socket.io support for connecting to backend API(s).

**Comment by zone117x** [comment]
I'm not sure how exactly the Explorer could use websockets in this case, as nextjs is performing server-side requests to render arbitrary pages requested externally, so it doesn't know in advance what socket topics to listen to. 

Something that would kinda help is disabling nextjs server-side rendering (at least the parts the perform API requests), so that our rate limiting on the API is applied to the clients requesting pages. 

And of course reduce the amount of aggressive client-side polling by using websockets where possible.

**Comment by andresgalante** [comment]
@beguene is this issue closed by the move to CSR?

**Comment by beguene** [comment]
Yes the move to CSR fixes the problem stated.
We will eventually move later to websockets but for different reasons.
