### ISSUE TITLE
Disable server-side API requests

### ISSUE THREAD

**Issue by zone117x** [hirosystems/explorer#626]
The Explorer's backend is performing a high volume of requests to the API and is a blocker for adjusting our API rate limiting. 

AFAIK this is a nextjs server-side rendering process which needs to be tweaked.

**Comment by CharlieC3** [comment]
Related https://github.com/hirosystems/explorer/issues/620

**Comment by markmhx** [comment]
Does this remain a relatively urgent issue? Or have we improved performance otherwise enough that this is now more of a nice-to-have?

**Comment by CharlieC3** [comment]
@markmhx 
> is a blocker for adjusting our API rate limiting

We were able to get around this blocker, but Explorer traffic makes up the single-most highest source of traffic for our APIs. So any effort that goes towards reducing server-side API requests from the Explorer will have a significant effect.

**Comment by beguene** [comment]
This will be partially mitigated by my PR https://github.com/hirosystems/explorer/pull/777
With this PR most pages will make only 1 api call server-side per page request (instead of 6 for some pages)
We are exploring some other solutions
* either full client-side 
* use direct db connection for perform SSR https://github.com/hirosystems/explorer/issues/783

**Comment by andresgalante** [comment]
@beguene I've added this to the board to close it when we move to full client-side

**Comment by andresgalante** [comment]
The next step is to remove SSR from the Microblocks page, and delete the old tx component
