### ISSUE TITLE
Allow users to submit feedback/report-a-bug

### ISSUE THREAD

**Issue by sabbyanandan** [hirosystems/explorer#693]
**Describe the solution you'd like**
As a developer, while using the Hiro Explorer, I would like to have an option to submit new feature requests or report a bug from Explorer directly.

**Additional context**
With this, any context-specific detail can be automatically extracted and included in the report, so I don't have to gather more information and/or screenshots to report either in Discord or GitHub. All this can be entirely automated.

**Comment by markmhx** [comment]
@sjwhitely Should we simply list "support@hiro.so" in the footer to provide a path here?

**Comment by landitus** [comment]
It could be like this in the footer. Still, note that though this solution it's low-effort, it would not allow for "any context-specific detail can be automatically extracted and included in the report" since it all depends on what the user types in the email or GH issue.

<img width="1312" alt="Screenshot 2022-04-26 at 15 51 06" src="https://user-images.githubusercontent.com/239215/165315451-f05615d1-59d3-4869-96f6-9048fb2f1dba.png">
